#importing libraries
import os
from pathlib import Path
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px # plotly for creating interactive plots
import requests


st.set_page_config(layout='wide', initial_sidebar_state='expanded')

plt.style.use('dark_background')

np.random.seed(42)

# get API URL, default to localhost for dev
API_URL = os.getenv("API_URL", "http://localhost:8000")

STATIC_DIR = Path(__file__).resolve().parent.parent / "static"
STYLE_PATH =  "./style.css"

def get_forecast():
    response = requests.get(f"{API_URL}/forecast/latest")
    return response.json()

def get_historical_data():
    response = requests.get(f"{API_URL}/history")
    return response.json()

def get_metrics():
    response = requests.get(f"{API_URL}/metrics")
    return response.json()

current_forecast = get_forecast()
historical_data = get_historical_data()
model_metrics = get_metrics()

def main():
    '''
    Main function to run the Streamlit app.
    '''
    st.title('South Africa CPI Nowcasting Application')
   #image = STATIC_DIR / "background_image.jpg"


  # with open(STYLE_PATH, encoding='utf-8') as f:
 #     st.markdown(f'<style>{f.read()}</style>',unsafe_allow_html=True)


    tab_home, tab_visuals = st.tabs(['Home','Visualizations'])
        
    with tab_home:
        st.write('The predictions of this web application are powered by a Catboost\
                Regressor model trained each on a time-series \
                of historic CPI values plus carefully engineered predictive features.\
                The model is retrained every month as new CPI data becomes available.')
        st.write('The data used to train the model is ingested from the [Stats SA website](https://www.statssa.gov.za/).')
        
        col1, col2 = st.columns((1,1),gap='medium')
        col1.metric("Last Train Date",model_metrics['last_train_date'])
        col2.metric("Model RMSE",model_metrics['rmse'])

        st.write('The table below shows the latest CPI forecast generated by the model:')
        st.table(current_forecast)
            
    
    with tab_visuals:

        st.write('The plot below shows the historical CPI values along with the latest forecast:')
        df = pd.DataFrame(historical_data)
        df['Date'] = pd.to_datetime(df['Date'])
        fig = px.line(df, x='Date', y='Value', color='Category', title='Historical CPI with Latest Forecast')
        st.plotly_chart(fig, use_container_width=True)

    st.markdown('''
    ---
    Created by [Isaac Oluwafemi Ogunniyi](https://linkedin.com/in/isaac-oluwafemi-ogunniyi)
    ''')

if __name__ == '__main__':
    main()
    