'''
Main API application for serving CPI forecasts and model metrics.
This FastAPI app provides endpoints for:
- Fetching the latest CPI forecasts
- Retrieving historical CPI data for visualization
- Accessing model performance metrics for MLOps monitoring

The API is designed to be lightweight and efficient,
 serving as the interface between the trained model and any frontend applications or dashboards.
'''
import json
import logging
from pathlib import Path
from typing import List, Dict, Any

import pandas as pd
from fastapi import FastAPI,  HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("CPI_API")

app = FastAPI(
    title="South Africa CPI Nowcasting API",
    description="API for serving monthly CPI forecasts and model performance metrics.",
    version="1.0.0"
)

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Path Configuration
BASE_DIR = Path(__file__).resolve().parent.parent
PREDICTIONS_DIR = BASE_DIR / "data" / "predictions"
METRICS_FILE = BASE_DIR / "models" / "model_metrics.json"
GOLD_DATA_FILE = BASE_DIR / "data" / "gold" / "CPI_gold.csv"

# --- Schema Definitions ---
class ForecastResponse(BaseModel):
    '''Defines the structure of the forecast response for API consumers.'''
    category: str
    date: str
    value: float

class ModelMetrics(BaseModel):
    '''Metadata about the last training run, useful for MLOps monitoring.'''
    last_train_date: str
    rmse: float
    features_used: List[str]
    hyperparameters: Dict[str, Any]

# --- Endpoints ---

@app.get("/", tags=["General"])
def read_root():
    '''Simple root endpoint to verify API is running.'''
    return {"message": "Welcome to the SA CPI Nowcasting API", "status": "online"}

@app.get("/health", tags=["General"])
def health_check():
    '''Simple health check endpoint to verify API is running.'''
    return {"status": "healthy", "timestamp": pd.Timestamp.now().isoformat()}

@app.get("/forecast/latest", response_model=List[ForecastResponse], tags=["Inference"])
def get_latest_forecast():
    """Returns the most recent nowcast generated by the pipeline."""
    try:
        # Find the most recent month folder in predictions
        month_folders = sorted([d for d in PREDICTIONS_DIR.iterdir() if d.is_dir()], reverse=True)
        if not month_folders:
            raise HTTPException(status_code=404, detail="No predictions found. Please run the pipeline.")
        
        latest_folder = month_folders[0]
        # Find the latest CSV inside that folder
        csv_files = sorted(latest_folder.glob("*.csv"), reverse=True)
        if not csv_files:
            raise HTTPException(status_code=404, detail="No forecast CSV files found.")

        df = pd.read_csv(csv_files[0])
        # Convert to list of dicts for Pydantic
        df['Date'] = df['Date'].astype(str)
        return df[['Category', 'Date', 'Value']].rename(columns=lambda x: x.lower()).to_dict(orient="records")
    
    except Exception as e:
        logger.error("Error fetching forecast: %s", e)

        raise HTTPException(status_code=500, detail=str(e))

@app.get("/history", tags=["Data"])
def get_historical_data():
    """Returns historical values to plot trends."""
    if not GOLD_DATA_FILE.exists():
        raise HTTPException(status_code=404, detail="Historical data file not found.")
    
    df = pd.read_csv(GOLD_DATA_FILE)
    return df[['Category', 'Date', 'Value']].to_dict(orient="records")

@app.get("/metrics", response_model=ModelMetrics, tags=["MLOps"])
def get_model_metrics():
    """Returns the metadata about the last training run."""
    if not METRICS_FILE.exists():
        raise HTTPException(status_code=404, detail="Model metrics not found.")
    
    with open(METRICS_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
